name: CI

on:
  push:
    branches:
      - main
      - validate/*
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - macos-latest
        - windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v3
      with:
        path: .yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-
    - uses: dotnet/nbgv@v0.4
      id: nbgv
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
        registry-url: https://npm.pkg.github.com
    - run: yarn --immutable
    - name: Build
      run: ./build_all.ps1
      shell: pwsh
    - name: Test
      run: yarn test

    - name: Stamping NPM versions
      run: .github/workflows/set_version.ps1 -Version ${{ steps.nbgv.outputs.NpmPackageVersion }}
      shell: pwsh
      if: runner.os == 'Linux'
    - name: Pack
      run: ./pack_all.ps1
      shell: pwsh
      if: runner.os == 'Linux'
    - name: Collect NPM package artifacts
      uses: actions/upload-artifact@v1
      with:
        name: NPM packages
        path: out
      if: runner.os == 'Linux'
  action_audit:
    runs-on: ubuntu-latest
    steps:
    - name: Dump environment
      run: env | sort
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
  publish:
    needs: build
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') # Ideally conditioned on: github.ref == format('refs/tags/v{0}', steps.nbgv.outputs.SemVer2)
    steps:
    - name: Download NPM package tgz files
      uses: actions/download-artifact@v1
      with:
        name: NPM packages
    - name: Prepare to publish to npmjs.org
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
        registry-url: https://registry.npmjs.org
    - name: Publish NPM packages to npmjs.org
      run: |
        Get-ChildItem *.tgz |% {
          npm publish $_
          if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
          }
        }
      shell: pwsh
      working-directory: NPM packages
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
