name: Publish

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v1
      with:
        path: .yarn/cache
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-
    - uses: aarnott/nbgv@v0.3
      id: nbgv
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        registry-url: https://registry.npmjs.org
      if: github.ref == format('refs/tags/v{0}', steps.nbgv.outputs.SemVer2)
    - run: yarn
      if: github.ref == format('refs/tags/v{0}', steps.nbgv.outputs.SemVer2)
    - name: Build
      run: ./build_all.ps1
      shell: pwsh
      if: github.ref == format('refs/tags/v{0}', steps.nbgv.outputs.SemVer2)
    - name: Stamping NPM versions
      run: .github/workflows/set_version.ps1 -Version ${{ steps.nbgv.outputs.NpmPackageVersion }}
      shell: pwsh
      if: github.ref == format('refs/tags/v{0}', steps.nbgv.outputs.SemVer2)
    - name: Pack
      run: ./pack_all.ps1
      shell: pwsh
      if: github.ref == format('refs/tags/v{0}', steps.nbgv.outputs.SemVer2)
    - name: Publish NPM packages to npmjs.org
      run: |
        Get-ChildItem *.tgz |% {
          npm publish $_
          if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
          }
        }
      shell: pwsh
      working-directory: out
      if: github.ref == format('refs/tags/v{0}', steps.nbgv.outputs.SemVer2)
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
